name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Compile Java
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile robot code
        run: ./gradlew compileJava

  test:
    name: Test Java
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run tests on robot code
        run: ./gradlew test -PrunTests 

  format:
    name: Check Format Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Fetch all history and metadata
        run: |
          git checkout -b pr
          git branch -f main origin/main
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Run formatter
        run: ./gradlew spotlessCheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Set up PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
      - name: Run PMD
        run: |
          pmd-bin-6.55.0/bin/run.sh pmd -d ./src -R pmd-ruleset.xml -f text -failOnViolation true -maxViolations 20
